# ------------------------------------------------
# docker-compose for ModelPolisher release version
# update docker hub images for new releases and change image accordingly
# ------------------------------------------------
version: '3'
services:
  biggdb:
    image: mephenor/bigg_docker:1.6
    container_name: modelpolisher_biggdb
    ports:
      - 1310:5432
  adb:
    image: mephenor/adb_docker:0.1.1
    container_name: modelpolisher_adb
    ports:
      - 1013:5432
  java:
    image: mephenor/modelpolisher:2.0.1
    depends_on:
      - biggdb
      - adb
    container_name: modelpolisher_java
    stdin_open: true
    tty: true
